esphome:
  name: telephone
  friendly_name: telephone
      
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "JIfaMgf9LImo+uUI6efK/+1c1v9nYnYNiNFQK56xzYk="

ota:
  - platform: esphome
    password: "28cae50d7289dd27f986761948b7d2dc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Telephone Fallback Hotspot"
    password: "Ws2cDekp9TIE"

captive_portal:


# -------------------------
# Inputs
# -------------------------

# Analog input for speaker detection
sensor:
  - platform: adc
    pin: GPIO34
    name: "Speaker Voltage"
    id: speaker_voltage
    sampling_mode: max
    update_interval: 50ms
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

binary_sensor:
  # Hook switch input
  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
    name: "Hook"
    id: hook
    on_press:
      then:
        - script.execute: hook_down
    on_release:
      then:
        - script.execute: hook_up

  # Dial pulse input
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    name: "Dial"
    id: dial
    on_press:
      then:
        - script.execute: dial_pulse

# -------------------------
# I2C Bus for Keypad (ADG2188)
# -------------------------
i2c:
  sda: 21
  scl: 3
  scan: true
  frequency: 50kHz

i2c_device:
  id: adg2188
  address: 0x70

# -------------------------
# Outputs (Bell)
# -------------------------
output:
  - platform: gpio
    pin: 25
    id: bell_1

  - platform: gpio
    pin: 26
    id: bell_2

# -------------------------
# Constants
# -------------------------
globals:
  - id: ring_min_voltage
    type: float
    initial_value: "0.1"

  - id: pulse_count # counts pulses from dial
    type: int
    initial_value: "0"

  - id: pulse_timer_running # true when pulse counting timer is running
    type: bool
    initial_value: "false"

  - id: ringing # true when the DECT phone is ringing
    type: bool
    initial_value: "false"

  - id: bell_required # true when the bell simulation is running
    type: bool
    initial_value: "false"

  - id: bell_active # true when the bell is actually making a sound as part of the UK cadence simulation
    type: bool
    initial_value: "false"

  - id: bell_direction # can be either 1 or 2 depending on which direction the bell dinger is pointing
    type: int
    initial_value: "1"

  - id: control_byte # for ADG2188 control
    type: uint8_t
    initial_value: "0"

# -------------------------
# HA buttons
# -------------------------

button:
  - platform: template
    name: "Keypad 0"
    id: kp_0
    on_press:
      then:
        - script.execute: key_press
          key: "0"
  - platform: template
    name: "Keypad 1"
    id: kp_1
    on_press:
      then:
        - script.execute: key_press
          key: "1"
  - platform: template
    name: "Keypad 2"
    id: kp_2
    on_press:
      then:
        - script.execute: key_press
          key: "2"
  - platform: template
    name: "Keypad 3"
    id: kp_3
    on_press:
      then:
        - script.execute: key_press
          key: "3"
  - platform: template
    name: "Keypad 4"
    id: kp_4
    on_press:
      then:
        - script.execute: key_press
          key: "4"
  - platform: template
    name: "Keypad 5"
    id: kp_5
    on_press:
      then:
        - script.execute: key_press
          key: "5"
  - platform: template
    name: "Keypad 6"
    id: kp_6
    on_press:
      then:
        - script.execute: key_press
          key: "6"
  - platform: template
    name: "Keypad 7"
    id: kp_7
    on_press:
      then:
        - script.execute: key_press
          key: "7"
  - platform: template
    name: "Keypad 8"
    id: kp_8
    on_press:
      then:
        - script.execute: key_press
          key: "8"
  - platform: template
    name: "Keypad 9"
    id: kp_9
    on_press:
      then:
        - script.execute: key_press
          key: "9"
  - platform: template
    name: "Keypad *"
    id: kp_star
    on_press:
      then:
        - script.execute: key_press
          key: "*"
  - platform: template
    name: "Keypad #"
    id: kp_hash
    on_press:
      then:
        - script.execute: key_press
          key: "#"
  - platform: template
    name: "Keypad SoftMenuLeft"
    id: kp_sbl
    on_press:
      then:
        - script.execute: key_press
          key: "SBL"
  - platform: template
    name: "Keypad SoftMenuRight"
    id: kp_sbr
    on_press:
      then:
        - script.execute: key_press
          key: "SBR"
  - platform: template
    name: "Keypad Up"
    id: kp_up
    on_press:
      then:
        - script.execute: key_press
          key: "UP"
  - platform: template
    name: "Keypad Down"
    id: kp_down
    on_press:
      then:
        - script.execute: key_press
          key: "DOWN"
  - platform: template
    name: "Keypad Left"
    id: kp_left
    on_press:
      then:
        - script.execute: key_press
          key: "LEFT"
  - platform: template
    name: "Keypad Right"
    id: kp_right
    on_press:
      then:
        - script.execute: key_press
          key: "RIGHT"
  - platform: template
    name: "Keypad Talk"
    id: kp_talk
    on_press:
      then:
        - script.execute: key_press
          key: "TALK"
  - platform: template
    name: "Keypad End"
    id: kp_end
    on_press:
      then:
        - script.execute: key_press
          key: "END"
  - platform: template
    name: "Keypad Intercom"
    id: kp_intercom
    on_press:
      then:
        - script.execute: key_press
          key: "INTERCOM"
  - platform: template
    name: "Keypad Speakerphone"
    id: kp_spphone
    on_press:
      then:
        - script.execute: key_press
          key: "SPPHONE"
  - platform: template
    name: "Keypad Recall"
    id: kp_recall
    on_press:
      then:
        - script.execute: key_press
          key: "RECALL"


# -------------------------
# Scripts
# -------------------------
interval:
    # 25Hz bell ring
  - interval: 20ms  # Half-period for 25Hz
    then:
      - lambda: |-
          if (id(bell_active)) {
            // Toggle bell_1
            if(id(bell_direction) == 1) {
              id(bell_1).turn_on();
              id(bell_2).turn_off();
              id(bell_direction) = 2;
              ESP_LOGD("main","Bell ding"); 
            } else {
              id(bell_1).turn_off();
              id(bell_2).turn_on(); 
              id(bell_direction) = 1;
              ESP_LOGD("main","Bell dong");
            }
          } else {
            // Ensure both off when not ringing
            id(bell_1).turn_off();
            id(bell_2).turn_off();
          }

     # Sound detection
  - interval: 50ms
    then:
      - lambda: |-
          id(ringing) = id(speaker_voltage).state > id(ring_min_voltage);
          if (id(ringing)) {
            ESP_LOGD("main","Ringing detected");
            id(ringing_stopped).stop();
            if(id(hook).state && !id(bell_required)) {
              id(bell_required) = true;
              ESP_LOGI("main","Ringing detected. Phone on-hook. Starting bell ringing");
              id(ring_bell).execute();
            }
          } else {
            if(id(bell_required)) {
              ESP_LOGI("main","No Ringing detected. Starting timer");
              id(ringing_stopped).execute();
            }
          }

script:
    #  Bell ringing script with UK cadence
  - id: ring_bell
    mode: queued
    then:
      - logger.log: Bell phase 1
      - lambda: 'id(bell_active) = true;'
      - delay: 400ms
      - logger.log: Bell phase 2
      - lambda: 'id(bell_active) = false;'
      - delay: 200ms
      - logger.log: Bell phase 3
      - lambda: 'id(bell_active) = true;'
      - delay: 400ms
      - logger.log: Bell phase 4
      - lambda: 'id(bell_active) = false;'
      - delay: 2000ms
      - if:
          condition:
            lambda: 'return id(bell_required);'
          then:
            - script.execute: ring_bell


  - id: ringing_stopped
    mode: single
    then:
      - delay: 1s   # wait 1 second to ensure ringing has really stopped
      - lambda: |-
          ESP_LOGI("main","Ringing stopped");
          id(bell_required) = false;
          id(ring_bell).stop();
          id(bell_active) = false;

  - id: key_press
    mode: single
    parameters:
      key: string
    then:
      - lambda: |-
          ESP_LOGI("main","Key Press: %s", key.c_str()); 
          uint8_t x=0; 
          uint8_t y=0;
          
          if(key =="SBL") { x=0; y=3; }
          else if(key =="SBR") { x=1;  y=3; }
          else if(key =="UP") { x=0; y=4; }
          else if(key =="DOWN") { x=1; y=4; }
          else if(key =="LEFT") { x=2; y=5; }
          else if(key =="RIGHT") { x=1; y=6; }
          else if(key =="TALK") { x=3; y=4; }
          else if(key =="END") { x=4; y=7; }
          else if(key =="1") { x=0; y=0; }
          else if(key =="3") { x=0; y=2; }
          else if(key =="4") { x=3; y=0; }
          else if(key =="5") { x=3; y=1; }
          else if(key =="6") { x=3; y=2; }
          else if(key =="7") { x=1; y=0; }
          else if(key =="8") { x=1; y=1; }
          else if(key =="9") { x=1; y=2; }
          else if(key =="0") { x=2; y=1; }
          else if(key =="*") { x=2; y=0; }
          else if(key == "#") { x=2; y=2; }
          else if(key =="SPPHONE") { x=2; y=3; }
          else if(key =="INTERCOM") { x=3; y=3; }
          else if(key =="RECALL") { x=2; y=4; }
          else {
            ESP_LOGW("main","Unknown key: %s", key.c_str());
            return;
          }

          // See ADG2188 datasheet.
          // bit 7 : DATA   (1 bit) Switch on = true; switch off = false;
          // bit 6-3 : AX   (4 bits, AX3..AX0)
          // bit 2-0 : AY   (3 bits, AY2..AY0)

          id(control_byte) = (x << 3) | y;

          uint8_t i2cPackets[2];
          i2cPackets[0] = id(control_byte) | 0x80; // Switch on
          i2cPackets[1] = 0x01; // apply immediately

          id(adg2188).write(i2cPackets, 2);
        
      - delay: 100ms
      - lambda: |-
          uint8_t i2cPackets[2];
          i2cPackets[0] = id(control_byte); // Switch off
          i2cPackets[1] = 0x01; // apply immediately

          id(adg2188).write(i2cPackets, 2);

  # Hang up
  - id: hook_down
    then:
      - logger.log:
          level: INFO
          format: "Hook DOWN"
      - script.execute: 
          id: key_press
          key: "END"
                          
  # Lift receiver
  - id: hook_up
    then:
      - logger.log:
          level: INFO
          format: "Hook UP"
      - if:
          condition: 
            lambda: 'return id(bell_required);'
          then:
            - script.execute: 
                id: key_press
                key: "TALK"
          else:
            - script.execute: 
                id: hook_up_action_not_ringing

  - id: hook_up_action_not_ringing
    then:
      - script.execute: 
          id: key_press
          key: "INTERCOM"
      - delay: 200ms
      - script.execute: 
          id: key_press
          key: "INTERCOM"

  # Count pulses from dial
  - id: dial_pulse
    mode: queued
    then:
      - lambda: |-
          ESP_LOGI("main","Dial pulse detected");
          if (!id(pulse_timer_running)) {
            id(pulse_count) = 1;
            id(pulse_timer_running) = true;
          } else {
            id(pulse_count) += 1;
          }
      - script.execute: pulse_finished

  - id: pulse_finished
    mode: restart
    then:
      - delay: 1s   # wait 1 second for no more pulses
      - lambda: |-
          ESP_LOGI("pulse", "Pulses counted: %d", id(pulse_count));
          // Reset for next series
          id(pulse_timer_running) = false;
          std::string number_to_dial = to_string(id(pulse_count));
          id(key_press).execute(number_to_dial);
          id(pulse_count) = 0;

